<?php
$campaignData = $block->getDetails();
$campaignData = $campaignData->getData();
    // $specificSendgridApiKey = NULL;

    // // Filter the array based on sendgrid_list_id
    // $filteredCampaignData = array_filter($campaignData, function ($campaignItem) use ($specificSendgridApiKey) {
    //     return $campaignItem['sendgrid_list_id'] == $specificSendgridApiKey;
    // });

    echo '<pre>';
    print_r($campaignData);
    
foreach ($campaignData as $campaignItem) {
    $senderEmail = $campaignItem['sender_email'];
    $cpruleID = $campaignItem['cart_price_rule_id'];
    $sendgridListID = $campaignItem['sendgrid_list_id'];
    $emailTemplate = $campaignItem['email_template'];
    $formName = $campaignItem['email_template'];
    $PopuPHeading = $campaignItem['heading'];
    $PopuPHeadingColor = $campaignItem['heading_color'];
    $SubHeading = $campaignItem['sub_heading_color'];
    $AddImage = $campaignItem['add_image'];
    $BackgroundColor = $campaignItem['background_color'];
    $Question = $campaignItem['question'];
    $Questiontype = $campaignItem['question_type'];
    $ButtonColor = $campaignItem['button_color'];
    $ButtonColor = $campaignItem['button_text'];
    $Disclaimer = $campaignItem['disclaimer'];
    $DisclaimerColor = $campaignItem['disclaimer_color'];
    $PopupDelay = $campaignItem['popup_delay'];
    $DisplayMode = $campaignItem['display_mode'];
}
if ($DisplayMode == 1) {
    echo $block->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('tech9logy_newsletterpopup')
    ->toHtml();
} else {
    echo "NO";
}
?>
