<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$thankYouDescription = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('tech9logycouponcode/general_settings/thank_you_description', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
?>
<div class="thank-you-message">
    <h1><?= $escaper->escapeHtml($thankYouDescription); ?></h1>
    <div class="buttons">
        <a href="/">Home</a>
        <a href="/couponcode/index">Back</a>
    </div>
</div>

<style>
.thank-you-message {
    padding: 150px;
}

.buttons {
    display: flex;
    justify-content: center;
    margin-top: 20px;
}

.buttons a {
    display: inline-block;
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    text-decoration: none;
    margin: 0 10px;
    border-radius: 5px;
}

.buttons a:hover {
    background-color: #0056b3;
}
</style>
