<?php
$campaignData = $block->getDetails()->getData();
$cookieName = "popupDisplayed";
$cookieValue = "true";

if (!empty($campaignData)) {
    foreach ($campaignData as $campaignItem) {
        $senderEmail = $campaignItem["sender_email"];
        $cpruleID = $campaignItem["cart_price_rule_id"];
        $sendgridListID = $campaignItem["sendgrid_list_id"];
        $emailTemplate = $campaignItem["email_template"];
        $formName = $campaignItem["email_template"];
        $PopuPHeading = $campaignItem["heading"];
        $PopuPHeadingColor = $campaignItem["heading_color"];
        $SubHeading = $campaignItem["sub_heading"];
        $AddImage = $campaignItem["add_image"];
        $BackgroundColor = $campaignItem["background_color"];
        $Question = $campaignItem["question"];
        $Questiontype = $campaignItem["question_type"];
        $ButtonColor = $campaignItem["button_color"];
        $ButtonText = $campaignItem["button_text"];
        $Disclaimer = $campaignItem["disclaimer"];
        $DisclaimerColor = $campaignItem["disclaimer_color"];
        $DisplayBlockName = $campaignItem["cms_block_id"];
        $PopupDelay = $campaignItem["popup_delay"];
        $DisplayMode = $campaignItem["popup_mode"];
        $imageUrl = $this->getBaseUrl() . "pub/media/" . $AddImage;
        $display = $campaignItem["display_mode"];
        $closeOption = $campaignItem["close_popup"];
        $homeorother = $campaignItem["display_mode_home"];
        $welcomepage = $campaignItem["sendgrid_mode"];
        $visitedPages = $campaignItem["page_visiting"];
        $templateversion = 1;
    }
} else {
    return "";
}

// Determine where to display the popup
if ($homeorother == 1) {
    // Display popup on every page and also when $homeorother is 1
    $displayPopup = true; ?>
<div id="sw-popup" class="welcome-popup-bx" style="background-image: url('https://images.pexels.com/photos/574069/pexels-photo-574069.jpeg?auto=compress&cs=tinysrgb&w=400'); background-repeat: no-repeat; backround-size:cover; display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 9999; background-color: #fff; padding: 20px;  background-size:cover;    max-width: 550px;
    width: 100%;">
        <div class="welcome-popup-bx-inner">
            <div class="close-btn">
                <img src="<?php echo $this->getViewFileUrl(
                    "Tech9logy_CouponCode::images/close.png"
                ); ?>" />
            </div>
            <div class="welcome-popup-text">
                <h2><?= $PopuPHeading ?></h2>
                <p class="subscribe-newsletter-tag-line"><?= $SubHeading ?></p>
                <form action="couponcode/subscriber/new" enctype="multipart/form-data" novalidate method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="">
                    <div class="form-group">
                        <input name="email" type="email" id="popup_newsletter_email" placeholder="<?php echo $block->escapeHtml(
                            __(" Enter address ")
                        ); ?>" data-validate="{required:true, 'validate-email':true}" />
                        <button class="action subscribe primary sw-btn-base sw-btn-primary sw-fill-out" title="<?= $block->escapeHtml(
                            __(" SUBSCRIBE ")
                        ) ?>" type="submit">
                            <span><?= $ButtonText ?></span>
                        </button>
                        
                    </div>
                    <p class="privacy-tag-line"><?= $Disclaimer ?></p>
                </form>
            </div>
            <!--<div class="welcome-popup-figure">
                <img src="<?= $imageUrl ?>" />
            </div>-->
        </div>
</div>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            // Check if the cookie exists
            if (document.cookie.indexOf("<?php echo $cookieName; ?>=<?php echo $cookieValue; ?>") === -1) {
                setTimeout(function () {
                    document.getElementById('sw-popup').style.display = 'block';

                    // Set a cookie to track popup display
                    var now = new Date();
                    now.setMonth(now.getMonth() + 1); // Add one month
                    var expires = "expires=" + now.toUTCString();
                    document.cookie = "<?php echo $cookieName; ?>=<?php echo $cookieValue; ?>; " + expires + "; path=/";
                    // Check if closeOption is 1, then close popup only on close button click
                    <?php if ($closeOption == 1): ?>
                        // Add event listener to the close button
                        var closeButton = document.querySelector('.close-btn');
                        closeButton.addEventListener('click', function () {
                            document.getElementById('sw-popup').style.display = 'none';
                        });
                    <?php endif; ?>

                    // Close popup when user clicks anywhere if closeOption is 0
                    <?php if ($closeOption == 0): ?>
                        document.addEventListener('click', function (event) {
                            if (!event.target.closest('.welcome-popup-bx')) {
                                document.getElementById('sw-popup').style.display = 'none';
                            }
                        });
                    <?php endif; ?>
                }, <?php echo $PopupDelay *
                    1000; ?>); // Convert seconds to milliseconds
            }
        });
    </script>
    <?php
} elseif (
    $homeorother == 0 &&
    $this->getRequest()->getFullActionName() == "cms_index_index"
) {
    // Display popup only on the home page
    $displayPopup = true;
} else {
    // Do not display popup on other pages
    $displayPopup = false;
}
?>

<?php if ($displayPopup): ?>
    <?php if ($DisplayMode == 2): ?>
        <div id="popup-content" style="display: none;">
            <?= $this->getLayout()
                ->createBlock("Magento\Cms\Block\Block")
                ->setBlockId($DisplayBlockName)
                ->toHtml() ?>
        </div>

        <script>
            document.addEventListener("DOMContentLoaded", function () {
                // Check if the cookie exists
                if (document.cookie.indexOf("<?php echo $cookieName; ?>=<?php echo $cookieValue; ?>") === -1) {
                    setTimeout(function () {
                        document.getElementById('popup-content').style.display = 'block';

                        // Set a cookie to track popup display
                        var now = new Date();
                        now.setMonth(now.getMonth() + 1); // Add one month
                        var expires = "expires=" + now.toUTCString();
                        document.cookie = "<?php echo $cookieName; ?>=<?php echo $cookieValue; ?>; " + expires + "; path=/";
                        // Check if closeOption is 1, then close popup only on close button click
                        <?php if ($closeOption == 1): ?>
                            var closeButton = document.querySelector('.close-btn');
                            closeButton.addEventListener('click', function () {
                                document.getElementById('popup-content').style.display = 'none';
                            });
                        <?php endif; ?>
                    }, <?php echo $PopupDelay *
                        1000; ?>); // Convert seconds to milliseconds
                }
            });
        </script>
    <?php else: ?>
        <?php if (
            $display == 0 ||
            $this->getRequest()->getFullActionName() == "cms_index_index"
        ): ?>
           <div id="sw-popup" class="welcome-popup-bx" style="background-image: url('https://images.pexels.com/photos/574069/pexels-photo-574069.jpeg?auto=compress&cs=tinysrgb&w=400'); background-repeat: no-repeat; backround-size:cover; display: none; position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 9999; background-color: #fff; padding: 20px;  background-size:cover;    max-width: 550px;
    width: 100%;">
        <div class="welcome-popup-bx-inner">
            <div class="close-btn">
                <img src="<?php echo $this->getViewFileUrl(
                    "Tech9logy_CouponCode::images/close.png"
                ); ?>" />
            </div>
            <div class="welcome-popup-text">
                <h2><?= $PopuPHeading ?></h2>
                <p class="subscribe-newsletter-tag-line"><?= $SubHeading ?></p>
                <form action="couponcode/subscriber/new" enctype="multipart/form-data" novalidate method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="">
                    <div class="form-group">
                        <input name="email" type="email" id="popup_newsletter_email" placeholder="<?php echo $block->escapeHtml(
                            __(" Enter address ")
                        ); ?>" data-validate="{required:true, 'validate-email':true}" />
                        <button class="action subscribe primary sw-btn-base sw-btn-primary sw-fill-out" title="<?= $block->escapeHtml(
                            __(" SUBSCRIBE ")
                        ) ?>" type="submit">
                            <span><?= $ButtonText ?></span>
                        </button>
                        
                    </div>
                    <p class="privacy-tag-line">Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                </form>
            </div>
            <!--<div class="welcome-popup-figure">
                <img src="<?= $imageUrl ?>" />
            </div>-->
        </div>
</div>

            <script>
                document.addEventListener("DOMContentLoaded", function () {
                    // Check if the cookie exists
                    if (document.cookie.indexOf("<?php echo $cookieName; ?>=<?php echo $cookieValue; ?>") === -1) {
                        setTimeout(function () {
                            document.getElementById('sw-popup').style.display = 'block';

                            // Set a cookie to track popup display
                            var now = new Date();
                            now.setMonth(now.getMonth() + 1); // Add one month
                            var expires = "expires=" + now.toUTCString();
                            document.cookie = "<?php echo $cookieName; ?>=<?php echo $cookieValue; ?>; " + expires + "; path=/";
                             // Check if closeOption is 1, then close popup only on close button click
                             <?php if ($closeOption == 1): ?>
                                // Add event listener to the close button
                                var closeButton = document.querySelector('.close-btn');
                                closeButton.addEventListener('click', function () {
                                    document.getElementById('sw-popup').style.display = 'none';
                                });
                            <?php endif; ?>
                        }, <?php echo $PopupDelay *
                            1000; ?>); // Convert seconds to milliseconds

                         // Close popup when user clicks anywhere if closeOption is 0
                         <?php if ($closeOption == 0): ?>
                            document.addEventListener('click', function (event) {
                                if (!event.target.closest('.welcome-popup-bx')) {
                                    document.getElementById('sw-popup').style.display = 'none';
                                }
                            });
                        <?php endif; ?>
                    }
                });
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>

<style>
@import url('https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap');

.newsletter-modal .modal-inner-wrap{
    max-width:700px; 
    width:100%;}

  
.welcome-popup-bx-inner{
    max-width: 600px; 
    width: 100%; 
    margin: 0px auto; 
    display: flex; 
    flex-flow: wrap; 
    position: relative;
}

.welcome-popup-bx-inner .close-btn {
    width: 16px;
    height: 16px;
    background-color: white;
    position: absolute;
    top: 5px;
    right: 5px;
    padding: 0px;
    box-sizing: border-box;
    cursor: pointer;
}
.welcome-popup-text { 
    width: 100%; 
    padding:15px;
    background-color:#ffffff96; 
    box-sizing: border-box;
}

.popup-newsletter{ margin: 0 auto !important;}





.newsletter-modal .modal-header { padding: 0px; 
    width: 50px; 
    height: 50px; 
    position: absolute; 
    top: 0px; 
    right: 0px; 
    z-index: 1; 
    background-color: #000; 
}

.newsletter-modal .modal-header .action-close { padding: 14px; }
.newsletter-modal .modal-header .action-close:before { color: #fff; 
    font-size: 23px; 
    padding: 0px !important; 
}

.welcome-popup-text .form-group{
    display: flex;
    display: -webkit-box;
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flex;
    flex-flow: wrap;
    position:relative;
    width: 100%;
}
.welcome-popup-text h2 {
    margin-top: 0;
    margin-bottom: 10px;
    font-size: 24px;
    font-weight: bold;
}

.welcome-popup-text p{    margin-bottom: 10px;    font-size: 15px !important;}

.welcome-popup-text .form-group input{width:100%; height:50px; padding:5px 130px 5px 10px; border-radius:5px;}
.welcome-popup-text .form-group input:focus{box-shadow: none;}
.welcome-popup-text .form-group button {
    max-width: 120px;
    width: 100%;
    position: absolute;
    background-color: #f53d3d !important;
    border: 1px solid #f53d3d !important;
    right: 10px;
    top: 50%;
    transform: translate(0px, -50%);
    -webkit-transform: translate(0px, -50%);
    -moz-transform: translate(0px, -50%);
    -ms-transform: translate(0px, -50%);
    -o-transform: translate(0px, -50%);
}
.welcome-popup-text .form-group button:hover, .welcome-popup-text .form-group button:active, .welcome-popup-text .form-group button:focus{
    background-color:#c32020 !important;  border:1px solid #c32020 !important;
}
 
p.privacy-tag-line {
    margin-bottom: 0;
    margin-top: 10px;
    font-size: 10px;
    color: #707070;
}

</style>
