<style>

    body{ margin:0px;}
    @import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap');
    *{ font-family: "Lato", sans-serif; box-sizing: border-box;}    
    img{ max-width:100%;}
    
    .newletter-popup-section { height: 100%; display: flex; flex-flow: wrap; align-items: center; justify-content: center; padding:0px 15px; width: 100%; position: fixed; top: 0px; left: 0px; z-index: 9;}
    .newletter-popup-section:before { content: ''; background-color: #00000094; width: 100%; height: 100%; display: block; position: absolute; top: 0px; left: 0px; z-index: -1; }
    .newletter-popup-row{ display: flex; display: -webkit-box; display: -webkit-flex; display: -moz-flex; display: -ms-flex; flex-flow: wrap; align-items: center; max-width:1000px; width:100%; margin:0px auto; background-color: #fff; position:relative; border-left: solid 10px #1e73be;}
    .new-popup-left { width: 50%; padding: 30px;}
    .new-popup-left .no-thanks { text-align: center; padding-top: 15px;}
    .new-popup-left .no-thanks a{ color:#9f9f9f; font-size: 14px;}
    .new-popup-right { width: 50%; padding: 30px; background-color: #1e73be;}
    .new-popup-right h1{ font-size:30px; margin:0px 0px 15px; color:#fff; font-weight:900;}
    .new-popup-right p{ font-size:16px; margin:0px; color:#fff; line-height:24px;}
    .newletter-popup-row .close-btn { position: absolute; top: 10px; right: 10px; background-color: #00000024; padding: 6px; width: 25px; height: 25px; border-radius: 5px; cursor:pointer;}
    .newletter-popup-row .close-btn img {vertical-align: super;}
    .email-form{ margin:0px;}
    .email-form .form-group .input-bx { width: 100%; padding: 0px 15px; font-size: 16px; height: 50px; border: solid 1px #ccc; border-radius: 5px; background-color: #fff;}
    .email-form .form-group .input-bx:focus{ outline:none;}
    .email-form .form-group .submit-btn { background-color: #1e73be; font-size: 18px; font-weight:bold; color:#fff; height: 50px; border: solid 1px #1e73be; border-radius: 5px; width:100%; margin-top:15px; cursor:pointer;}
    .email-form .form-group .submit-btn:hover { background-color: transparent; color:#1e73be; border: solid 1px #1e73be;}
    
    @media screen and (max-width: 767px)
    {
        .new-popup-right h1{ font-size:24px;}
        .new-popup-left { width: 100%; padding: 20px; order:2;}
        .new-popup-right { width: 100%; padding: 20px; order:1;}
        .newletter-popup-row { border-left: none; border-bottom: solid 10px #1e73be;}
    }
    
</style>

<div class="newletter-popup-section">
    <div class="newletter-popup-row">
        <div class="new-popup-left">
        <form class="email-form" action="couponcode/subscriber/new" enctype="multipart/form-data" novalidate method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="">
                <div class="form-group">
                <input name="email" type="email" class="input-bx" id="popup_newsletter_email" placeholder="<?= $escaper->escapeHtml(
                    __(" Enter address ")
                ); ?>" data-validate="{required:true, 'validate-email':true}" />
                    <button class="submit-btn">Submit</button>
                </div>
            </form>
            <div class="no-thanks">
                <a href="#">No, I am not interested</a>
            </div>
        </div>
        <div class="new-popup-right">
            <h1>Our Newsletter</h1>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        </div>
        <div class="close-btn">
        <img src="<?= $block->getViewFileUrl(
            "Tech9logy_CouponCode::images/close-iconwhite.png"
        ); ?>" />
        </div>
    </div>
</div>
