<style>
    @import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap');
    *{ font-family: "Lato", sans-serif; box-sizing: border-box;}    
    img{ max-width:100%;}
    .newsletter-section{ padding:0px 15px; }
    .newsletter-row{ display: flex; display: -webkit-box; display: -webkit-flex; display: -moz-flex; display: -ms-flex; flex-flow: wrap; align-items: center; max-width:800px; width:100%; margin:50px auto; background-color: #fff; position: relative;}
    .newsletter-row .close-btn {    width: 30px;    height: 30px;    position: absolute;    top: 10px;    right: 10px;    background-color: #00000021;    border-radius: 5px;    padding: 8px;    cursor: pointer;}
    .newsletter-section .newsletter-left{ width:40%;}
    .newsletter-section .newsletter-left img{ vertical-align: middle;}
    .newsletter-section .newsletter-right{ width:60%; padding:30px;}
    .newsletter-section .newsletter-right h1{ margin:0px 0px 15px; font-size:30px; font-weight:900; color:#333;}
    .newsletter-section .newsletter-right p{ font-size:16px; line-height:26px; color:#333;}
    .newsletter-form .form-group{ margin-bottom:0px; position:relative;}
    .newsletter-form .form-group .input-bx { width: 100%; height: 50px; border-radius: 0px; border: solid 1px #ccc; padding: 0px 15px; font-size:16px;}
    .newsletter-form .form-group .input-bx:focus{ outline:none;}
    .newsletter-form .form-group .submit-btn { position: absolute; top: 0px; right: 0px; height: 50px; max-width: 100px; width: 100%; font-size: 16px; font-weight: 900; text-transform: uppercase; background-color: #ff7300; border: none; color: #fff; cursor:pointer;}
    .newsletter-form .form-group .submit-btn:hover{ background-color: #d16206;}
    .newsletter-section { padding: 0px 15px; position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 9; display: flex; flex-flow: wrap; align-items: center; justify-content: space-around; }
    .newsletter-section:before {    content: '';    background-color: #00000099;    width: 100%;    height: 100%;    display: block;    position: absolute;    top: 0px;    left: 0px;    z-index: -1;}

    

    @media screen and (max-width: 767px)
    {
        .newsletter-section .newsletter-left{ width:100%;}
        .newsletter-section .newsletter-left img{ width:100%;}
        .newsletter-section .newsletter-right{ width:100%; padding:20px;}
        .newsletter-section .newsletter-right h1{ font-size:20px;}
        .newsletter-section .newsletter-right p{ font-size:14px; line-height:24px;}
    }
    
</style>

<div class="newsletter-section">
    <div class="newsletter-row">
    <div class="close-btn">
                <img src="<?= $block->getViewFileUrl(
                    "Tech9logy_CouponCode::images/close.png"
                ); ?>" />
            </div>
        <div class="newsletter-left">
        <img src="<?= $block->getViewFileUrl(
            "Tech9logy_CouponCode::images/version1.jpg"
        ); ?>" />
        </div>
        <div class="newsletter-right">
            <h1>What is Lorem Ipsum?</h1>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
            <form class="newsletter-form">
            <form class="newsletter-form" action="couponcode/subscriber/new" enctype="multipart/form-data" novalidate method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="">
                <div class="form-group">
                    <input name="email" type="email" class="input-bx" id="popup_newsletter_email" placeholder="<?= $escaper->escapeHtml(
                        __(" Enter address ")
                    ); ?>" data-validate="{required:true, 'validate-email':true}" />
                    <button class="submit-btn">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>