<style>
    body { margin: 0px; }
    @import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap');
    * { font-family: "Lato", sans-serif; box-sizing: border-box; }    
    img { max-width: 100%; }
    
    .email-section { height: 100%; display: flex; flex-flow: wrap; align-items: center; justify-content: center; padding: 0px 15px; position: fixed; top: 0px; left: 0px; width: 100%; z-index: 9; }
    .email-section:before { content: ''; background-color: #00000042; width: 100%; height: 100%; display: block; position: absolute; top: 0px; left: 0px; z-index: -1; }
    
    .email-row { display: flex; display: -webkit-box; display: -webkit-flex; display: -moz-flex; display: -ms-flex; flex-flow: wrap; align-items: center; max-width: 550px; width: 100%; margin: 0px auto; background-color: #fff; border-radius: 10px; overflow: hidden; }
    .email-figure { text-align: center; padding: 25px; width: 100%; background-color: #04c9c7; position: relative; }
    .email-row .close-btn { width: 30px; height: 30px; position: absolute; top: 10px; right: 10px; background-color: #00000021; border-radius: 5px; padding: 8px; cursor: pointer; }
    .email-row .close-btn img { height: auto; }
    .email-figure img { height: 100px; margin: 0px auto; }
    .email-figcaption { padding: 25px; width: 100%; }
    .email-figcaption h1 { text-align: center; margin: 0px 0px 15px; font-size: 30px; font-weight: 900; color: #333; }
    .email-figcaption p { text-align: center; margin: 0px 0px 25px; font-size: 15px; line-height: 24px; color: #333; }
    .email-form { margin: 0px; }
    .email-form .form-group .input-bx { width: 100%; padding: 0px 15px; font-size: 16px; height: 50px; border: solid 1px #ccc; border-radius: 5px; background-color: #fff; }
    .email-form .form-group .input-bx:focus { outline: none; }
    .email-form .form-group .submit-btn { background-color: #04c9c7; font-size: 18px; font-weight: bold; color: #fff; height: 50px; border: solid 1px #04c9c7; border-radius: 5px; width: 100%; margin-top: 15px; cursor: pointer; }
    .email-form .form-group .submit-btn:hover { background-color: transparent; color: #04c9c7; border: solid 1px #04c9c7; }
    
    
    @media screen and (max-width: 767px) {
        .email-figcaption h1 { font-size: 24px; }
    }
</style>

<div class="email-section">
    <div class="email-row">
        <div class="email-figure">
            <img src="<?= $block->getViewFileUrl("Tech9logy_CouponCode::images/version3.png"); ?>" />
            <div class="close-btn">
                <img src="<?= $block->getViewFileUrl("Tech9logy_CouponCode::images/close.png"); ?>" />
            </div>
        </div>
        <div class="email-figcaption">
            <h1>Our Newsletter</h1>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <form class="email-form" action="couponcode/subscriber/new" enctype="multipart/form-data" novalidate method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="emailForm">
                <div class="form-group">
                <input name="email" type="email" class="input-bx" id="popup_newsletter_email" placeholder="<?= $escaper->escapeHtml(
                    __(" Enter address ")
                ); ?>" data-validate="{required:true, 'validate-email':true}" />
                    <button class="submit-btn">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>


