<?php
/**
 * @author Sachindra Awasthi
 * @copyright Copyright (c) 2023 Tech9logy (https://www.tech9logy.com/)
 * @package Tech9logy_CouponCode
 */
?>

<div class="reports-content tech9logy-couponcode-generate">
    <?= $block->getChildHtml('grid.filter.form') ?>
</div>

<?php //echo $block->getGridHtml() ?>

<script>
require([
    'jquery',
    'mage/backend/validation',
    "prototype"
], function(jQuery){

//<![CDATA[
    jQuery('#filter_form').mage('validation', {errorClass: 'mage-error'});
    function filterFormSubmit() {
        var filters = $$('#filter_form input', '#filter_form select');
        var elements = [];
        for(var i in filters){
            if(filters[i].value && filters[i].value.length && !filters[i].disabled) elements.push(filters[i]);
        }
        if (jQuery('#filter_form').valid()) {
            setLocation('<?= /* @escapeNotVerified */ $block->getFilterUrl(); ?>filter/'+Base64.encode(Form.serializeElements(elements))+'/');
        }
    }
//]]>
    window.filterFormSubmit = filterFormSubmit;
});
</script>
